FORMAT: 1A
HOST: http://www.google.com

# Alfa


## Ille vana et vinoque inopem

Lorem markdownum latus opem perstet suo pervia [nostros](http://www.lipsum.com/)
et humus, quotiensque suo. Cognoscet harenas ferunt, quod, ita lumina vertitur
et sororum. Tuentur sagittis pro sub nunc pendere illis, dei fato peractum.
Summo voto rigorem pastores.

- Pedibus nec eadem potitur
- Vidit sorte iaculo nomenque et sacra illa
- Summis cur tendite adsonat
- Domum nec molles attonitos figit inhaerebat coeunt
- Sororum inposito et currere vestris

Talia hostis exire fraternis templorum recubare simul, *paritura habes* qua
satis, horruit; tum vota haut. Adveniens inflati solos intravit diriguit Tritona
coruscant mixtaque; pressum ista draconum nescia vindicat neque ululasse cura.
Ossibus in et tamen.

## Sumite ancipiti omnis roseum doloris remoliri instare

Meae cuspidis effugit Bacchi, mille, est ille vivit extinctum! Natis et nova cum
monuit qua, qui tardus Titan silet ictu cum Adoni amplexu, ingesta!

Caraeque ramos edentem, per petebar aliquid in visa fulmina teneros in vestrae
cognoscite mater et. Munere obstitimus Pylio iunctamque socios coniunx restant
monte lacrimas crede tam amisit. Defensae misceat? Cui aurae proximus Me vires
remos est cognoscendo animos; *iam*.

    if (-4 + pppoeFileDcim > popMysqlPup(duplex.windows(5), teraflops)) {
        virtualizationKibibyteVirtual.gateMemoryPmu(4, matrixIo);
        lte = bridge(sliDelete - kilobyte);
    }
    if (forum(pinterest_beta_hoc, encoding_device) + tweakRgb) {
        hexadecimal_partition_compile.sdk_thin = 866028;
        rootkitCluster = file + browser_pppoe(software_del, zif_ipod, meme);
        mtu = 5 + friend_emulation_export - 5;
    } else {
        xp.power_system(responsive_crt, page_packet);
    }
    modem += thyristor_floppy;

Fertilis Iovis habitat, nobis monte tibi, suum, exstant in hostibus sensurum
volvitur trepidare nereides. Gramina
[cupidine](http://www.raynelongboards.com/)? Sub usum relictum; hic suo una
subit ex nec fatebitur.


# Group Notes
Notes related resources of the **Notes API**

## Notes Collection [/notes?id={id}&testingGroup={testtingGroup}&collection={collection}]

+ Parameters

    + id = `1` (number, required) ... An unique identifier of the message
    
    + testingGroup = `testing` (optional) ... We have added the query URI template parameter - `limit`. This parameter is used for limiting the number of results returned by some actions on this resource. It does not affect every possible action of this resource therefore we will discuss it only at the particular action level below.
        + values 
            + `testing`
            + `staging`
            + `live`
            + `deploy`
            + `circleci`
            + `travisci`            
    
    + collection (string or something different as Instance Collection Object Class, `notes`) ... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras tincidunt laoreet dui vitae faucibus.

### List all Notes [GET]
+ Response 200 (application/json)

        [{
          "id": 1, "title": "Jogging in park"
        }, {
          "id": 2, "title": "Pick-up posters from post-office"
        }]

### Create a Note [POST]
+ Request (application/json)

        { "title": "Buy cheese and bread for breakfast." }

+ Response 201 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }

## Note [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Note to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

    + Header

            X-My-Header: The Value

    + Body

            { "id": 2, "title": "Pick-up posters from post-office" }

### Remove a Note [DELETE]
+ Response 204
