FORMAT: 1A

HOST: http://snippets.example.com/

# Testing snippet

## Basic methods

# /resource

## GET

+ Response 200 (application/json)

        { "items": [
          { "url": "/shopping-cart/1", "product":"2ZY48XPZ", "quantity": 1, "name": "New socks", "price": 1.25 }
        ] }

## HEAD

+ Response 204

## POST

+ Request (application/json)

        { "product":"1AB23ORM", "quantity": 2 }

+ Response 201 (application/json)

        { "status": "created", "url": "/shopping-cart/2" }

## PUT

+ Request (application/json)

        { "product":"1AB23ORM", "quantity": 2 }

+ Response 200 (application/json)

        { "status": "created", "url": "/shopping-cart/2" }

## DELETE

+ Response 204
